In [60]:
from sqlalchemy import create_engine, text

# Formato de conexión: postgresql://usuario:contraseña@host:puerto/base
engine = create_engine("postgresql://postgres:qweiopasdkln1001@localhost:5432/mi_base")

In [61]:

with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database();"))
    print(result.scalar())  # debería mostrar 'mi_base'

mi_base

In [62]:
import pandas as pd

# Leer tabla a DataFrame
df = pd.read_sql("SELECT * FROM clientes", engine)

# Guardar DataFrame en la base
df.to_sql("clientes", engine, if_exists="append", index=False)

0

In [63]:
df

Empty DataFrame
Columns: [id, nombre, correo, fecha_registro]
Index: []

In [64]:
base = pd.read_excel("Proyectos Verano 202511.xlsx")
base

,Grupo,Nombre oficial de la Organización Socio Formadora (OSF) con la que se realizará el Proyecto Solidario,"Nombre del Proyecto Solidario: \n (NOTA: no es el nombre de la OSF ni es el listado de actividades a realizar, ni la clave del CRN, el nombre debe ser atractivo para el estudiante)",Tipo de vulnerabilidad de la población atendida (scroll hacia abajo):,Objetivo del Proyecto Solidario: \n (El objetivo es el cambio deseado que se quiere lograr con el proyecto solidario respecto al problema identificado),Lugar de trabajo: \nNota: En caso de aplicar; dirección donde el estudiante realizará el Servicio Social,"Enlista (1., 2., 3., ...) y describe de forma breve las principales actividades/acciones a realizar por parte del estudiantado durante el Proyecto Solidario","Si aplica, Indique el horario: de _________ a _______. (Ejemplo: lunes a viernes de 8 am a 12 pm)",Indique el horario: de _________ a _______. Ejemplo: lunes a viernes de 8 am a 12 pm,"Teniendo en cuenta que los alumnos están en fase de enfoque (empiezan a llevar contenidos de su carrera ), especifica si se requiere la participación de estudiantes de alguna(s) carrera(s) para llevar a cabo el proyecto solidario: (https://sitios.itesm.mx",Habilidades o competencias que el alumno requiere para participar en el proyecto:,Cupo de estudiantes: Colocar el número de estudiantes que pueden participar en la experiencia (como recomendación no manejar menos de 10 participantes por grupo),Modelo en que se llevará a cabo el proyecto solidario: (el mixto debe ser 70% presencial y 30% en línea),Lugar de trabajo: \nColoca la dirección en donde trabajará el estudiantado:,Duración de la experiencia:,Horas máximas que el estudiante puede acreditar dependiendo de su desempeño:,Comentarios adicionales:
0,Por definir,Centro de Autonomía Personal y Social (CAPYS A...,Vida Independiente para personas con discapaci...,Discapacidad mental,Contribuir a la calidad de los servicios que C...,"CAPYS VALLE: \nPilares 310, Col. Del Valle, Al...",1. Participar en una sesión de inducción. \n2....,CAPYS trabaja de Lunes a viernes de 9:00 a 6:0...,"Matutino (9am a 1pm), Vespertino (1pm a 5pm), ...","Todas, LED, LC, LEI","Vocación de servicio, empatía, capacidad de ad...",10,PSP | Proyecto Solidario Presencial,"CAPYS VALLE: \nPilares 310, Col. Del Valle, Al...",3 semanas hasta 60 hrs,Hasta 60,"Con respecto al ""Lugar de Trabajo"", para quien..."
1,Por definir,Centro de Autonomía Personal y Social (CAPYS A...,Vida plena e inclusiva: Empoderando capacidades,Discapacidad mental,Fomentar la inclusión y autodeterminación de p...,"Instituto Tlalpan: \nCuitláhuac #15, Colonia T...",1. Capacitarse sobre discapacidad.\n2. Apoyo e...,De lunes a viernes de 7:00 a 14:00 hrs,Matutino (9am a 1pm),"Todas, LED, LC, LEI",- Empatía y sensibilidad social: Comprender la...,10,PSP | Proyecto Solidario Presencial,"Instituto Tlalpan: \nCuitláhuac #15, Colonia ...",3 semanas hasta 60 hrs,Hasta 60,Buscamos capacitar a los estudiantes para que ...
2,Por definir,Centro de Autonomía Personal y Social (CAPYS A...,Vida plena e inclusiva: Transición a la vida a...,Discapacidad mental,Fomentar la inclusión y autodeterminación de p...,Construyendo Puentes UIC\nAv. Insurgentes Su...,1. Capacitarse sobre discapacidad.\n2. Apoyo e...,Lunes a viernes de 7:00am a 3:00pm,Matutino (9am a 1pm),"Todas, LED, LC",- Empatía y sensibilidad social: Comprender la...,4,CLIP | Proyecto Solidario Mixto,"Construyendo Puentes UIC\nAv. Insurgentes Sur,...",3 semanas hasta 60 hrs,Hasta 60,Buscamos capacitar a los estudiantes para que ...
3,Por definir,CEPI (Comunidad Educativa y Psicopedagógica In...,Manejo de redes y apoyo en la inclusión de per...,Discapacidad mental,Sensibilización a la población respecto a este...,"CEPI (Mimosa 33 Olivar de los Padres, Álvaro O...",1. Apoyo en aula con guía de un titular educa...,Lunes a viernes en horario matutino (8:30 a 14...,Matutino (9am a 1pm),Todas,Compromiso y respeto a la diversidad,5,CLIP | Proyecto Solidario Mixto,"Mimosa 33, Olivar de los Padres, Álvaro Obregó...",3 semanas hasta 60 hrs,Hasta 60,Agradecemos a los alumnos que se interesan en ...
4,Por definir,Clinica Mexicana de Autismo y Alteraciones del...,"Intervención psicoeducacional a niños, adolesc...",Personas con discapacidad,Las personas con TEA necesitan sus terapias de...,Van Dick 66 colonia santamaria nonoalco alcald...,Realizar intervención Psicoeducacional con per...,luneas a viernes de 9am a 2 pm,"Matutino (9am a 1pm), Por acordar con OSF",LPS,"Asaptabilidad, empatia, trabajo en equipo",5,PSP | Proyecto Solidario Presencial,Van Dick 66 colonia santamaria nonoalco alcald...,3 semanas hasta 60 hrs,Hasta 60,CLIMA es un lugar en donde no solo se pueden l...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,Por definir,Red para la Restauración Integral y Familiar A...,Inspira Comunicaciones,Niñas y Adolescentes,"Elaboración de campañas, contenido audiovisual...","Arbolillo 99, col LAS Hadas Coapa. Alcaldía Tl...",1. Crear de campañas \n2. Crear de contenido a...,lunes a viernes de 9 am a 2 pm,Matutino (9am a 1pm),"LAD, LDI, LRI, LC, LTM, IRS, ITC, LDE","Habilidades relaciones publicas, publicidad y ...",10,CLIP | Proyecto Solidario Mixto,Arbolillo 99. Colonia: Las Hadas Coapa. Alcald...,5 semanas hasta 200 hrs,Hasta 200,Los esperamos. Te sugerimos revisar que esta o...
70,Por definir,Tecnológico de Monterrey & Departamento Geoesp...,Patrones Hermosos Tec de Monterrey by Departam...,Niñas y Adolescentes,Impactar a niñas en edades de 13 a 17 años en ...,"Tec de Monterrey, Campus Ciudad de México",1. Diseñar contenidos\n2. Elaborar material re...,Lunes a viernes de 8:00 a 18:00 hrs. en los dí...,Completo (9 am a 7 pm),"IBT, IDS, IDM, IRS, ITC, ITD, IMD, IMT","Mujer estudiante de ingeniería, particularment...",55,PSP | Proyecto Solidario Presencial,"Tec de Monterrey, Campus Ciudad de México",5 semanas hasta 200 hrs,Hasta 200,El proyecto solidario surgió de la iniciativa ...
71,Por definir,Un Techo para mi país México\n,Juventudes en acción para superar la pobreza,Personas en situación de pobreza,Contribuir a superar la pobreza en México a pa...,Oficina de TECHO: https://maps.app.goo.gl/md3i...,1.- Promover la conciencia y acción social en ...,"Para acordar con la OSF, algunos días virtuale...",Por acordar con OSF,Todas,"Participación ciudadana, liderzago facilitador...",50,CLIP | Proyecto Solidario Mixto,Oficina de TECHO: https://maps.app.goo.gl/md3i...,5 semanas hasta 200 hrs,Hasta 200,Los esperamos. Te sugerimos revisar que esta o...
72,Por definir,Una Mirada Rett A.C.,Construyendo una Rett de apoyo para las infancias,Niñas y Adolescentes,Impulsar una red de apoyo que posibilite el de...,"Oficinas Institucionales, Alcaldía Benito Juárez",1. Investigar temas con relación a la atención...,lunes a viernes de 9 a 13hrs,Matutino (9am a 1pm),Todas,"empatía, pensamiento critico, trabajo en equipo.",15,PSP | Proyecto Solidario Presencial,"CDA. Emiliano Zapata 75 , col. Portales Norte ...",5 semanas hasta 200 hrs,Hasta 200,Los esperamos. Te sugerimos revisar que esta o...
73,Por definir,Vive Planeta,Cambiando el mundo desde tu trinchera,Medio ambiente,Que las y los alumnos participen activamente e...,no aplica,"1. Investigar sobre problemas sociales, altern...",no aplica.,Por acordar con OSF,"LAD, LRI, LC, LPE, IDS","Conocimiento y uso de Adobe Premiere, Capcut, ...",10,CLIN | Proyecto Solidario en Línea,No aplica.,5 semanas hasta 200 hrs,Hasta 200,Solo inscríbete si te interesa participar acti...

In [65]:
columnasNum = pd.DataFrame(base.columns)
columnasNum

                                                    0
0                                               Grupo
1   Nombre oficial de la Organización Socio Formad...
2    Nombre del Proyecto Solidario: \n (NOTA: no e...
3   Tipo de vulnerabilidad de la población atendid...
4   Objetivo del Proyecto Solidario: \n (El objeti...
5   Lugar de trabajo: \nNota: En caso de aplicar; ...
6   Enlista (1., 2., 3., ...) y describe de forma ...
7   Si aplica, Indique el horario: de _________ a ...
8   Indique el horario: de _________ a _______. Ej...
9   Teniendo en cuenta que los alumnos están en fa...
10  Habilidades o competencias que el alumno requi...
11  Cupo de estudiantes: Colocar el número de estu...
12  Modelo en que se llevará a cabo el proyecto so...
13  Lugar de trabajo: \nColoca la dirección en don...
14                       Duración de la experiencia:
15  Horas máximas que el estudiante puede acredita...
16                           Comentarios adicionales:

Nos quedamos unicamente con columnas que nos sirvan realmente

In [66]:
base = base.drop(columns=columnasNum.iloc[[0,3,4,5,6,7,8,10,13,16],0])
base

,Nombre oficial de la Organización Socio Formadora (OSF) con la que se realizará el Proyecto Solidario,"Nombre del Proyecto Solidario: \n (NOTA: no es el nombre de la OSF ni es el listado de actividades a realizar, ni la clave del CRN, el nombre debe ser atractivo para el estudiante)","Teniendo en cuenta que los alumnos están en fase de enfoque (empiezan a llevar contenidos de su carrera ), especifica si se requiere la participación de estudiantes de alguna(s) carrera(s) para llevar a cabo el proyecto solidario: (https://sitios.itesm.mx",Cupo de estudiantes: Colocar el número de estudiantes que pueden participar en la experiencia (como recomendación no manejar menos de 10 participantes por grupo),Modelo en que se llevará a cabo el proyecto solidario: (el mixto debe ser 70% presencial y 30% en línea),Duración de la experiencia:,Horas máximas que el estudiante puede acreditar dependiendo de su desempeño:
0,Centro de Autonomía Personal y Social (CAPYS A...,Vida Independiente para personas con discapaci...,"Todas, LED, LC, LEI",10,PSP | Proyecto Solidario Presencial,3 semanas hasta 60 hrs,Hasta 60
1,Centro de Autonomía Personal y Social (CAPYS A...,Vida plena e inclusiva: Empoderando capacidades,"Todas, LED, LC, LEI",10,PSP | Proyecto Solidario Presencial,3 semanas hasta 60 hrs,Hasta 60
2,Centro de Autonomía Personal y Social (CAPYS A...,Vida plena e inclusiva: Transición a la vida a...,"Todas, LED, LC",4,CLIP | Proyecto Solidario Mixto,3 semanas hasta 60 hrs,Hasta 60
3,CEPI (Comunidad Educativa y Psicopedagógica In...,Manejo de redes y apoyo en la inclusión de per...,Todas,5,CLIP | Proyecto Solidario Mixto,3 semanas hasta 60 hrs,Hasta 60
4,Clinica Mexicana de Autismo y Alteraciones del...,"Intervención psicoeducacional a niños, adolesc...",LPS,5,PSP | Proyecto Solidario Presencial,3 semanas hasta 60 hrs,Hasta 60
...,...,...,...,...,...,...,...
69,Red para la Restauración Integral y Familiar A...,Inspira Comunicaciones,"LAD, LDI, LRI, LC, LTM, IRS, ITC, LDE",10,CLIP | Proyecto Solidario Mixto,5 semanas hasta 200 hrs,Hasta 200
70,Tecnológico de Monterrey & Departamento Geoesp...,Patrones Hermosos Tec de Monterrey by Departam...,"IBT, IDS, IDM, IRS, ITC, ITD, IMD, IMT",55,PSP | Proyecto Solidario Presencial,5 semanas hasta 200 hrs,Hasta 200
71,Un Techo para mi país México\n,Juventudes en acción para superar la pobreza,Todas,50,CLIP | Proyecto Solidario Mixto,5 semanas hasta 200 hrs,Hasta 200
72,Una Mirada Rett A.C.,Construyendo una Rett de apoyo para las infancias,Todas,15,PSP | Proyecto Solidario Presencial,5 semanas hasta 200 hrs,Hasta 200
73,Vive Planeta,Cambiando el mundo desde tu trinchera,"LAD, LRI, LC, LPE, IDS",10,CLIN | Proyecto Solidario en Línea,5 semanas hasta 200 hrs,Hasta 200