In [111]:
from sqlalchemy import create_engine, text

# Formato de conexión: postgresql://usuario:contraseña@host:puerto/base
engine = create_engine("postgresql://postgres:qweiopasdkln1001@localhost:5432/mi_base")

with engine.connect() as conn:
    result = conn.execute(text("SELECT current_database();"))
    print(result.scalar())  # debería mostrar 'mi_base'

import pandas as pd

# Leer tabla a DataFrame
estudiantes = pd.read_sql("SELECT * FROM estudiantes", engine)
usuarios = pd.read_sql("SELECT * FROM usuarios", engine)
osf = pd.read_sql("SELECT * FROM organizaciones", engine)
proyectos = pd.read_sql("SELECT * FROM proyectos", engine)
inscripciones = pd.read_sql("SELECT * FROM inscripciones", engine)
# Guardar DataFrame en la base
# df.to_sql("clientes", engine, if_exists="append", index=False)

mi_base

In [112]:
import random

In [113]:
usuarios = usuarios.drop([0,1])
usuarios

     id_usuario           username    contraseña        tipo  activo
2             2  user2@example.com  default_pass  Estudiante    True
3             3  user3@example.com  default_pass  Estudiante    True
4             4  user4@example.com  default_pass  Estudiante    True
5             5  user5@example.com  default_pass  Estudiante    True
6             6  user6@example.com  default_pass  Estudiante    True
..          ...                ...           ...         ...     ...
140         140                     default_pass         OSF    True
141         141                     default_pass         OSF    True
142         142                     default_pass         OSF    True
143         143                     default_pass         OSF    True
144         144                     default_pass         OSF    True

[143 rows x 5 columns]

In [114]:
usuarios_clean

     id_usuario           username    contraseña        tipo  activo
2             2  user2@example.com  default_pass  Estudiante    True
3             3  user3@example.com  default_pass  Estudiante    True
4             4  user4@example.com  default_pass  Estudiante    True
5             5  user5@example.com  default_pass  Estudiante    True
6             6  user6@example.com  default_pass  Estudiante    True
..          ...                ...           ...         ...     ...
140         140                     default_pass         OSF    True
141         141                     default_pass         OSF    True
142         142                     default_pass         OSF    True
143         143                     default_pass         OSF    True
144         144                     default_pass         OSF    True

[143 rows x 5 columns]

In [115]:

# Normalizamos usuarios existentes
usuarios_clean = usuarios.copy()


# Aseguramos columnas necesarias

usuarios_clean["activo"] = True

# ---------------------------
# 2. Crear tabla estudiantes (hija)
# ---------------------------
estudiantes = estudiantes.drop(columns=["username"], errors="ignore")  # Eliminamos id_estudiante para evitar conflictos
# Usamos id_estudiante como id_usuario
estudiantes_hija = estudiantes.rename(columns={
    "id_estudiante": "id_usuario",
    "Correo": "username",
    "Matrícula": "matricula",
    "celular": "celular",
    "Hora de llegada": "hora_llegada",
    "Hora de Salida": "hora_salida"
})

# Agregamos tipo en usuarios
usuarios_estudiantes = pd.DataFrame({
    "id_usuario": estudiantes_hija["id_usuario"],
    "username": estudiantes_hija["username"],
    
    "contraseña": ["default_pass"] * len(estudiantes_hija),
    "tipo": ["Estudiante"] * len(estudiantes_hija),
    "activo": [True] * len(estudiantes_hija)
})

# ---------------------------
# 3. Crear tabla organizaciones (hija)
# ---------------------------

socioFormadores = osf.copy()
socioFormadores["id_usuario"] = pd.Series(range(101, len(socioFormadores) + 102))
socioFormadores["id_organizacion"] = [""] * len(socioFormadores)
socioFormadores.drop(columns=["Nombre OSF"], inplace=True)

usuarios_osf = pd.DataFrame({
    "id_usuario": socioFormadores["id_usuario"],
    "username": [""] * len(socioFormadores),
   
    "contraseña": ["default_pass"] * len(socioFormadores),
    "tipo": ["OSF"] * len(socioFormadores),
    "activo": [True] * len(socioFormadores)
})

# ---------------------------
# 4. Crear tabla admins (hija)
# ---------------------------

admins_hija = pd.DataFrame({
    "id_usuario": usuarios_clean[usuarios_clean["tipo"] == "Admin"]["id_usuario"],
    
})



# ---------------------------
# 5. Unir todos los usuarios
# ---------------------------

usuarios_final = pd.concat([usuarios_estudiantes, usuarios_osf, admins_hija], ignore_index=True)

In [116]:
usuarios

     id_usuario           username    contraseña        tipo  activo
2             2  user2@example.com  default_pass  Estudiante    True
3             3  user3@example.com  default_pass  Estudiante    True
4             4  user4@example.com  default_pass  Estudiante    True
5             5  user5@example.com  default_pass  Estudiante    True
6             6  user6@example.com  default_pass  Estudiante    True
..          ...                ...           ...         ...     ...
140         140                     default_pass         OSF    True
141         141                     default_pass         OSF    True
142         142                     default_pass         OSF    True
143         143                     default_pass         OSF    True
144         144                     default_pass         OSF    True

[143 rows x 5 columns]

In [117]:
estudiantes_hija

,id_usuario,celular,username,Matricula,hora_llegada,hora_salida
0,0,2932492407,user0@example.com,A26033714,00:00:00,00:00:01
1,1,7336015959,user1@example.com,A46881525,00:00:00,00:00:01
2,2,7122902095,user2@example.com,A43869769,00:00:00,00:00:01
3,3,5335212446,user3@example.com,A84862515,00:00:00,00:00:01
4,4,9506409436,user4@example.com,A14555236,00:00:00,00:00:01
...,...,...,...,...,...,...
96,96,8670705778,user96@example.com,A73583266,00:00:00,00:00:01
97,97,4562259808,user97@example.com,A22335199,00:00:00,00:00:01
98,98,9060057872,user98@example.com,A12286542,00:00:00,00:00:01
99,99,8125176411,user99@example.com,A39848439,00:00:00,00:00:01
100,100,9317584428,user100@example.com,A86499264,00:00:00,00:00:01

In [118]:
usuarios_final = usuarios_final.iloc[0:145,:]
usuarios_final

     id_usuario           username    contraseña        tipo activo
0             0  user0@example.com  default_pass  Estudiante   True
1             1  user1@example.com  default_pass  Estudiante   True
2             2  user2@example.com  default_pass  Estudiante   True
3             3  user3@example.com  default_pass  Estudiante   True
4             4  user4@example.com  default_pass  Estudiante   True
..          ...                ...           ...         ...    ...
140         140                     default_pass         OSF   True
141         141                     default_pass         OSF   True
142         142                     default_pass         OSF   True
143         143                     default_pass         OSF   True
144         144                     default_pass         OSF   True

[145 rows x 5 columns]

In [119]:


for i in range(len(socioFormadores)):
    random_id = random.choice(osf["id_organizacion"].tolist())
    socioFormadores["id_organizacion"].iloc[i] = random_id

C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  socioFormadores["id_organizacion"].iloc[i] = random_id
C:\Users\snava\AppData\Local\Temp\ipykernel_10784\2189165155.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.


In [120]:
socioFormadores

   id_organizacion  id_usuario
0               17         101
1               35         102
2                5         103
3                8         104
4               21         105
5               13         106
6               15         107
7               10         108
8                7         109
9                7         110
10              46         111
11              42         112
12              21         113
13              29         114
14              22         115
15              13         116
16              27         117
17              45         118
18              45         119
19              36         120
20               4         121
21              35         122
22              43         123
23              37         124
24              37         125
25              34         126
26               2         127
27              13         128
28               7         129
29               2         130
30              28         131
31               8         132
32               2         133
33               2         134
34              40         135
35              17         136
36              15         137
37               3         138
38              27         139
39              30         140
40              43         141
41              36         142
42               3         143
43              34         144
44              25         145

In [121]:
admins_hija

Empty DataFrame
Columns: [id_usuario]
Index: []

In [122]:
osf

    id_organizacion                                         Nombre OSF
0                 0  Centro de Autonomía Personal y Social (CAPYS A...
1                 1  CEPI (Comunidad Educativa y Psicopedagógica In...
2                 2  Clinica Mexicana de Autismo y Alteraciones del...
3                 3        Escuela Primaria de Tiempo Completo Somalia
4                 4                             Escuela Primaria Niger
5                 5                            Florecer Casa Hogar A.C
6                 6                                  Planta Física CCM
7                 7  Prevención del Delito, Policía de Proximidad d...
8                 8                            Tus buenas noticias IAP
9                 9                                              Ampre
10               10  Asociación Mexicana de la Enfermedad de Huntin...
11               13  Casa de Estudios, Investigación y promoción de...
12               14  Centro de Estudios para el Desarrollo Rural (C...
13               15           Centros de Integración Juvenil, Tlalpan
14               16  Coordinación General del Subsistema de Educaci...
15               17               De Aprendices Para Aprendices (DAPA)
16               19                                 Distrito Tlalpan\n
17               20         Escuela Primaria Estado de San Luis Potosí
18               21                           Escuela Primaria Ucrania
19               22                                 Pilares San Marcos
20               23               Promoción y Acción Comunitaria I.A.P
21               24                           Tecnológico de Monterrey
22               25                               Unidos somos iguales
23               26             Asociación Mexicana de Parkinson, A.C.
24               27  Asociación para Leer Escuchar Escribir y Recre...
25               28         Campamentos Tecnológico de Monterrey , CCM
26               29                                          Compostec
27               30          Conectadas, Mujeres por Más Mujeres, A.C.
28               31                               Contagiando Voluntad
29               32                                Deportivo Tolentino
30               33                                          Dianui AC
31               34                                        Domus Music
32               35                                         Fucam, A.C
33               36                           Fundación Bull and Bear
34               37                 Fundación Espera la Primavera A.C.
35               38  Fundación Renacimiento de Apoyo a la Infancia ...
36               39                           Fundación Sue Aguayo A.C
37               40               Instituto Mexicano del Seguro Social
38               41                            México sin sordera A.C.
39               42                                           Prepanet
40               43  Red para la Restauración Integral y Familiar A...
41               44  Tecnológico de Monterrey & Departamento Geoesp...
42               45                     Un Techo para mi país México\n
43               46                               Una Mirada Rett A.C.
44               47                                       Vive Planeta

In [123]:
inscripciones = pd.read_sql("SELECT * FROM inscripciones", engine)

inscripciones

     id_estudiante  id_proyecto
0                0           23
1                1           32
2                2           11
3                3           62
4                4           36
..             ...          ...
96              96           27
97              97           52
98              98           35
99              99           26
100            100           18

[101 rows x 2 columns]

In [133]:


# Conectamos a la base de respaldo
engine_copia = create_engine("postgresql://postgres:qweiopasdkln1001@localhost:5432/mi_base_backup_proyectos")

with engine_copia.connect() as conn:
    # 1. Limpieza total de tablas previas para evitar conflictos
    conn.execute(text("""
        DROP TABLE IF EXISTS inscripciones, proyectos, usuarios_organizaciones, 
                           admins, estudiantes, usuarios, organizaciones CASCADE;
    """))
    
    # 2. Crear tabla maestra: usuarios
    conn.execute(text("""
        CREATE TABLE usuarios (
            id_usuario SERIAL PRIMARY KEY,
            username VARCHAR(100) UNIQUE NOT NULL,
            correo VARCHAR(150),
            contraseña VARCHAR(255) NOT NULL,
            tipo VARCHAR(20) NOT NULL, -- Estudiante, Admin, OSF
            activo BOOLEAN DEFAULT TRUE
        );
    """))

    # 3. Crear tabla: organizaciones (OSF)
    conn.execute(text("""
        CREATE TABLE organizaciones (
            id_organizacion SERIAL PRIMARY KEY,
            nombre_osf VARCHAR(200) NOT NULL,
            correo_contacto VARCHAR(150)
        );
    """))

    # 4. Crear tablas hijas (Herencia)
    conn.execute(text("""
        CREATE TABLE estudiantes (
            id_estudiante INTEGER PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
            username VARCHAR(20),
            celular VARCHAR(20),
            hora_llegada TIME,
            hora_salida TIME
        );
        
        CREATE TABLE admins (
            id_admin INTEGER PRIMARY KEY REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
            rol VARCHAR(50),
            permisos_extra TEXT
        );
        
        CREATE TABLE usuarios_organizaciones (
            id_usuario INTEGER REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
            id_organizacion INTEGER REFERENCES organizaciones(id_organizacion) ON DELETE CASCADE,
            PRIMARY KEY (id_usuario, id_organizacion)
        );
    """))
    conn.commit()
    print("✔ Estructura relacional creada exitosamente.")

✔ Estructura relacional creada exitosamente.

In [134]:
# --- A. Organizaciones ---
osf_final = osf.rename(columns={
    "id_organizacion": "id_organizacion",
    "Nombre OSF": "nombre_osf",
    
})[['id_organizacion', 'nombre_osf']]

# --- B. Usuarios (Consolidado) ---
# Nota: Usamos los IDs que ya definiste en tus pasos anteriores
usuarios_final = usuarios_final.rename(columns={
    "id_usuario": "id_usuario",
    "username": "username",
    "correo": "correo",
    "contraseña": "contraseña",
    "tipo": "tipo",
    "activo": "activo"
})

# --- C. Estudiantes (Hija) ---
# Aseguramos que el ID se llame id_estudiante para la PK de la tabla hija
estudiantes_hija_final = estudiantes_hija.rename(columns={
    "id_usuario": "id_estudiante",
    "matricula": "username"
})[['id_estudiante', 'username', 'celular', 'hora_llegada', 'hora_salida']]

# --- D. Admins (Hija) ---
admins_hija_final = admins_hija.rename(columns={
    "id_usuario": "id_admin"
})
admins_hija_final["rol"] = "General" # Valores por defecto para cumplir con el esquema

In [127]:
# Modificación en la creación de usuarios_osf
usuarios_osf = pd.DataFrame({
    "id_usuario": socioFormadores["id_usuario"],
    # En lugar de "", generamos un username único temporal
    "username": [f"osf_user_{i}" for i in socioFormadores["id_usuario"]],
    "correo": [f"contacto_{i}@osf.com" for i in socioFormadores["id_usuario"]], # O usa el correo real si lo tienes
    "contraseña": ["default_pass"] * len(socioFormadores),
    "tipo": ["OSF"] * len(socioFormadores),
    "activo": [True] * len(socioFormadores)
})

In [129]:
usuarios_estudiantes

     id_usuario             username    contraseña        tipo  activo
0             0    user0@example.com  default_pass  Estudiante    True
1             1    user1@example.com  default_pass  Estudiante    True
2             2    user2@example.com  default_pass  Estudiante    True
3             3    user3@example.com  default_pass  Estudiante    True
4             4    user4@example.com  default_pass  Estudiante    True
..          ...                  ...           ...         ...     ...
96           96   user96@example.com  default_pass  Estudiante    True
97           97   user97@example.com  default_pass  Estudiante    True
98           98   user98@example.com  default_pass  Estudiante    True
99           99   user99@example.com  default_pass  Estudiante    True
100         100  user100@example.com  default_pass  Estudiante    True

[101 rows x 5 columns]

In [135]:
# --- VALIDACIÓN PRE-CARGA ---
# Unimos de nuevo para asegurar que usuarios_final tenga los datos corregidos
usuarios_final = pd.concat([usuarios_estudiantes, usuarios_osf, admins_hija], ignore_index=True)

# Eliminamos cualquier duplicado accidental en memoria
usuarios_final = usuarios_final.drop_duplicates(subset=['username'])
usuarios_final = usuarios_final.drop_duplicates(subset=['id_usuario'])

with engine_copia.connect() as conn:
    # Limpiamos todo para empezar de cero sin conflictos
    conn.execute(text("TRUNCATE TABLE usuarios_organizaciones, estudiantes, admins, usuarios, organizaciones CASCADE;"))
    conn.commit()

try:
    print("Iniciando carga de datos corregida...")
    
    # Orden jerárquico estricto
    osf_final.to_sql("organizaciones", engine_copia, if_exists="append", index=False)
    usuarios_final.to_sql("usuarios", engine_copia, if_exists="append", index=False)
    
    # Tablas hijas
    estudiantes_hija_final.to_sql("estudiantes", engine_copia, if_exists="append", index=False)
    
    # Relación intermedia (asegúrate que socioFormadores tenga los mismos id_usuario que usuarios_osf)
    relacion_osf = socioFormadores[['id_usuario', 'id_organizacion']]
    relacion_osf.to_sql("usuarios_organizaciones", engine_copia, if_exists="append", index=False)

    print("✔ ¡Éxito! Base de datos poblada sin conflictos de unicidad.")

except Exception as e:
    print(f"✘ Error durante la inserción: {e}")

Iniciando carga de datos corregida...
✔ ¡Éxito! Base de datos poblada sin conflictos de unicidad.